# Simple docker-compose.yml
# You can change your port or volume location

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
    networks:
      - uptime-kuma
      - backend
    environment:
      VIRTUAL_HOST: "uptime.monitoring.simulalab.org"
      LETSENCRYPT_HOST: "uptime.monitoring.simulalab.org"
      LETSENCRYPT_EMAIL: "it@simulalab.org"

networks:
  uptime-kuma:
  backend:
    external: true
    name: http-proxy_backend

volumes:
  uptime-kuma:
